// Package sqlflow provides a SQLite-backed storage layer built on top
// of database/sql. It wraps SQLite in WAL mode with separate read and write
// connections, serialised writes, and exponential-backoff retry logic.
//
// The two main abstractions are:
//
//   - DB[Queries, D]: a single SQLite database whose per-transaction accessor is Queries.
//     Use OpenDB to open (or create) a file, or TestDB for an in-memory database
//     in tests.
//
//   - Pool[Queries, D]: a per-key connection pool where each key (e.g. a user ID) maps
//     to its own SQLite file on disk. Connections are cached in a ristretto
//     TinyLFU cache and closed gracefully when evicted. Use NewPool to create
//     one, or TestPool in tests.
//
// All database access goes through Read and Write methods, that manage the transaction for
// the callers.
//
// Both types have encrypted variants: use OpenEncryptedDB and NewEncryptedPool
// instead of their plain counterparts. Encryption requires the jgiannuzzi fork
// of mattn/go-sqlite3 with SQLCipher support and WithDriver(MattnDriver).
//
// sqlflow has no built-in driver dependency. Import the SQLite driver of your
// choice and pass the corresponding DriverConfig via WithDriver:
//
//	import _ "github.com/mattn/go-sqlite3"              // mattn (default, CGo)
//	import _ "modernc.org/sqlite"                        // modernc (pure Go)
//	import _ "github.com/ncruces/go-sqlite3/driver"      // ncruces (WebAssembly)
//	import _ "github.com/ncruces/go-sqlite3/embed"
//
// If no WithDriver option is passed, sqlflow defaults to MattnDriver.
//
// Migrations are decoupled from the core: pass migrators.Goose(fsys) as an
// Option to run goose-based schema migrations on open, or implement your own
// OnOpen hook for any other migration tool.
package sqlflow

import (
	"context"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"maps"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/cenkalti/backoff/v4"
	"github.com/dgraph-io/ristretto/v2"
)

// testDBCounter generates unique in-memory database names for TestDB to ensure
// that parallel test calls do not share the same in-memory database (critical
// for modernc, which uses cache=shared for its in-memory DSN).
var testDBCounter atomic.Int64

// DBTX is the interface satisfied by both *sql.DB and *sql.Tx, allowing the
// same accessor type to be used within or outside a transaction.
type DBTX interface {
	ExecContext(context.Context, string, ...any) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...any) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...any) *sql.Row
}

// Querier is a function that builds a per-transaction accessor of type Queries from
// a D. It is called once per transaction inside Read and Write.
//
// D is the concrete DBTX type accepted by the accessor constructor — typically
// sqlflow.DBTX for hand-written code, or the package-local DBTX generated by
// sqlc. Using the package-local type lets you pass sqlc-generated New functions
// directly without any adapter wrapper.
type Querier[Queries any, D DBTX] func(tx D) *Queries

// DB is a SQLite database handle parameterised by a per-transaction accessor type
// Queries. It maintains two underlying sql.DB connections:
//
//   - wrdb: a single write connection (MaxOpenConns=1) with _txlock=immediate,
//     serialised by a mutex so that only one writer can hold the SQLite WAL
//     write lock at a time.
//   - rddb: an unbounded pool of read connections with _txlock=deferred,
//     allowing concurrent readers to proceed without blocking writers.
//
// Every operation runs inside a transaction. Write calls retry on transient
// SQLite busy errors using exponential backoff; Read calls retry indefinitely
// until the context is cancelled.
type DB[Queries any, D DBTX] struct {
	// querier constructs the per-transaction accessor from a D.
	querier Querier[Queries, D]

	// rddb is the read connection pool; uses _txlock=deferred to allow
	// concurrent readers.
	rddb *sql.DB

	// backoffRetries is the maximum number of write attempts before giving up.
	backoffRetries int

	// mu serialises access to wrdb so only one writer holds the SQLite WAL
	// write lock at a time.
	mu *sync.Mutex

	// wrdb is the single write connection; MaxOpenConns=1, _txlock=immediate.
	wrdb *sql.DB

	// path is the database file path provided to the constructor; ":memory:"
	// for in-memory test databases.
	path string

	// onClose holds the registered close hooks, fired at most once on Close.
	onClose closeFnList

	// closeOnce ensures onClose fires at most once across multiple Close calls.
	closeOnce sync.Once

	// driver is the active SQLite driver configuration, used to detect
	// permanent connection errors.
	driver DriverConfig
}

// TestDB creates an in-memory SQLite database and returns a DB ready for use
// in tests. Pass migrators.Goose(fsys) as an option to apply schema migrations.
//
// Panics on any error so test setup stays concise.
func TestDB[Queries any, D DBTX](querier Querier[Queries, D], opts ...Option) *DB[Queries, D] {
	driver := collectDriver(opts)
	params := collectDSNParams(opts)
	pragmas := collectPragmas(opts)

	dbName := fmt.Sprintf("testdb%d", testDBCounter.Add(1))
	conn, err := sql.Open(driver.name, driver.memoryDSN(dbName, "immediate", params, pragmas))
	if err != nil {
		panic(err)
	}
	conn.SetMaxOpenConns(1)

	onOpen, onClose := collectHooks(opts)

	if err := onOpen.run(":memory:", conn); err != nil {
		conn.Close()
		panic(fmt.Sprintf("onOpen hook: %v", err))
	}

	return &DB[Queries, D]{
		querier:        querier,
		rddb:           conn,
		mu:             &sync.Mutex{},
		wrdb:           conn,
		backoffRetries: 1,
		path:           ":memory:",
		onClose:        onClose,
		driver:         driver,
	}
}

// OpenDB opens (or creates) the SQLite database at dbName and returns an open DB.
// Pass migrators.Goose(fsys) as an option to run schema migrations.
func OpenDB[Queries any, D DBTX](dbName string, querier Querier[Queries, D], opts ...Option) (*DB[Queries, D], error) {
	return openDB(dbName, querier, nil, opts)
}

// OpenEncryptedDB opens (or creates) the SQLCipher-encrypted SQLite database at
// dbName and returns an open DB. Pass migrators.Goose(fsys) as an option to
// run schema migrations.
//
// Encryption requires a SQLCipher-enabled driver. Use the jgiannuzzi fork of
// mattn/go-sqlite3 with WithDriver(MattnDriver) (the default). Other drivers
// return ErrEncryptionNotSupported.
func OpenEncryptedDB[Queries any, D DBTX](dbName string, querier Querier[Queries, D], key []byte, opts ...Option) (*DB[Queries, D], error) {
	return openDB(dbName, querier, key, opts)
}

// Option carries configuration for a DB or Pool instance. Construct one with
// OnOpen, OnClose, WithDSNParams, WithPragma, or WithDriver; passing no options
// is always valid.
type Option struct {
	onOpen    func(path string, db *sql.DB) error
	onClose   func(path string, db *sql.DB)
	dsnParams string
	pragmas   [][2]string
	driver    *DriverConfig
}

// OnOpen registers fn to be called with the database file path and the live
// write connection once all connections are established and the DB is ready for
// use. If fn returns a non-nil error, the connections are closed and the error
// is propagated from the constructor.
//
// Multiple OnOpen options run in registration order.
// For in-memory databases created by TestDB the path is ":memory:".
func OnOpen(fn func(path string, db *sql.DB) error) Option {
	return Option{onOpen: fn}
}

// OnClose registers fn to be called after both database connections are
// closed. fn receives the database file path and the (now-closed) write
// connection. Multiple OnClose options run in registration order.
// fn fires at most once even if Close is called multiple times. Use OnClose
// to release resources tied to this DB's lifetime (e.g. lock files).
func OnClose(fn func(path string, db *sql.DB)) Option {
	return Option{onClose: fn}
}

// WithDSNParams adds extra SQLite DSN parameters to every connection opened by
// this DB or Pool. The _txlock and _journal parameters are always controlled
// by sqlflow and cannot be overridden. All other parameters — including _sync,
// _busy_timeout, and _cache_size — take the value from the last WithDSNParams
// option that sets them, overriding sqlflow's defaults. The _key and _cipher
// parameters are silently ignored; use OpenEncryptedDB or NewEncryptedPool for
// encrypted databases.
//
// params is a URL query string, e.g. "_foreign_keys=1&_cache_size=50000".
// This option is driver-specific: mattn uses flat params (_foreign_keys=1)
// while modernc and ncruces use _pragma format (_pragma=foreign_keys(1)).
// Use WithPragma for a portable alternative that works with all drivers.
func WithDSNParams(params string) Option {
	return Option{dsnParams: params}
}

// WithPragma sets a SQLite PRAGMA on every connection opened by this DB or
// Pool. It works with all supported drivers regardless of their DSN format —
// mattn renders it as _name=value; modernc and ncruces render it as
// _pragma=name(value).
//
// The journal_mode PRAGMA is always controlled by sqlflow and cannot be
// overridden via WithPragma.
func WithPragma(name, value string) Option {
	return Option{pragmas: [][2]string{{name, value}}}
}

// WithDriver selects the SQLite driver used by this DB or Pool. If not set,
// sqlflow defaults to MattnDriver. You must separately import the driver
// package in your program for the driver to be registered with database/sql.
func WithDriver(d DriverConfig) Option {
	return Option{driver: &d}
}

// DriverConfig holds everything sqlflow needs to open connections for a
// specific SQLite driver. Use the pre-built vars (MattnDriver, ModerncDriver,
// NcrucesDriver) rather than constructing one directly.
type DriverConfig struct {
	// name is the driver name passed to sql.Open.
	name string

	// buildDSN builds a file-backed database DSN.
	buildDSN func(path, txlock string, params url.Values, pragmas [][2]string) string

	// buildCipherDSN builds an encrypted database DSN. Nil if unsupported.
	buildCipherDSN func(path, txlock string, key []byte, params url.Values, pragmas [][2]string) string

	// memoryDSN builds an in-memory database DSN.
	// memoryDSN builds an in-memory DSN. name is a unique identifier that
	// drivers requiring shared-cache in-memory databases (e.g. modernc) must use
	// to isolate parallel TestDB calls from each other.
	memoryDSN func(name, txlock string, params url.Values, pragmas [][2]string) string

	// isPermanentErr reports whether err is a connection error that should
	// never be retried.
	isPermanentErr func(error) bool
}

// MattnDriver configures sqlflow to use the mattn/go-sqlite3 driver. It is the
// default when no WithDriver option is passed. Import the driver in your program:
//
//	import _ "github.com/mattn/go-sqlite3"
var MattnDriver = DriverConfig{
	name: "sqlite3",
	buildDSN: func(path, txlock string, params url.Values, pragmas [][2]string) string {
		return mattnBuildDSN(path, txlock, params, pragmas)
	},
	buildCipherDSN: func(path, txlock string, key []byte, params url.Values, pragmas [][2]string) string {
		return mattnBuildCipherDSN(path, txlock, key, params, pragmas)
	},
	memoryDSN: func(_, txlock string, params url.Values, pragmas [][2]string) string {
		return mattnBuildDSN(":memory:", txlock, params, pragmas)
	},
	isPermanentErr: func(err error) bool {
		// SQLITE_NOTADB (error 26) — file is not a database or cipher key is wrong.
		return strings.Contains(err.Error(), "file is not a database")
	},
}

// ModerncDriver configures sqlflow to use the modernc.org/sqlite driver
// (pure Go, no CGo). Import the driver in your program:
//
//	import _ "modernc.org/sqlite"
var ModerncDriver = DriverConfig{
	name: "sqlite",
	buildDSN: func(path, txlock string, params url.Values, pragmas [][2]string) string {
		return pragmaBuildDSN(path, txlock, params, pragmas)
	},
	buildCipherDSN: nil,
	memoryDSN: func(name, txlock string, params url.Values, pragmas [][2]string) string {
		return pragmaInMemoryDSN(true, name, txlock, params, pragmas)
	},
	isPermanentErr: func(error) bool { return false },
}

// NcrucesDriver configures sqlflow to use the github.com/ncruces/go-sqlite3
// driver (WebAssembly, no CGo). Import the driver in your program:
//
//	import _ "github.com/ncruces/go-sqlite3/driver"
//	import _ "github.com/ncruces/go-sqlite3/embed"
var NcrucesDriver = DriverConfig{
	name: "sqlite3",
	buildDSN: func(path, txlock string, params url.Values, pragmas [][2]string) string {
		return pragmaBuildDSN(path, txlock, params, pragmas)
	},
	buildCipherDSN: nil,
	memoryDSN: func(_, txlock string, params url.Values, pragmas [][2]string) string {
		return pragmaInMemoryDSN(false, ":memory:", txlock, params, pragmas)
	},
	isPermanentErr: func(error) bool { return false },
}

// Close calls the OnClose hook (if any) exactly once, then closes both the
// read and write database connections. It waits for any in-flight operations
// to complete before returning.
func (db *DB[Queries, D]) Close() error {
	db.closeOnce.Do(func() { db.onClose.run(db.path, db.wrdb) })

	return errors.Join(db.rddb.Close(), db.wrdb.Close())
}

// Checkpoint runs PRAGMA wal_checkpoint(TRUNCATE) under the write mutex.
// WAL frames are moved into the main database file and, if all readers are
// done, the WAL file is reset to zero size.
func (db *DB[Queries, D]) Checkpoint(ctx context.Context) error {
	db.mu.Lock()
	defer db.mu.Unlock()

	_, err := db.wrdb.ExecContext(ctx, "PRAGMA wal_checkpoint(TRUNCATE)")

	return err
}

// Read executes f inside a read-only deferred transaction. It retries on
// transient SQLite busy errors using exponential backoff until ctx is
// cancelled. Errors returned by f are treated as permanent and not retried.
func (db *DB[Queries, D]) Read(ctx context.Context, f func(*Queries) error) error {
	return backoff.Retry(func() error {
		return db.transaction(ctx, db.rddb, f)
	}, backoff.WithContext(backoff.NewExponentialBackOff(), ctx))
}

// Write executes f inside an immediate (exclusive) transaction under the write
// mutex. It retries on transient SQLite busy errors up to backoffRetries times
// with exponential backoff. Errors returned by f are treated as permanent and
// cause an immediate rollback with no retry.
func (db *DB[Queries, D]) Write(ctx context.Context, f func(*Queries) error) error {
	var err error

	b := backoff.WithContext(backoff.NewExponentialBackOff(), ctx)
	for range db.backoffRetries {
		db.mu.Lock()
		err = db.transaction(ctx, db.wrdb, f)
		db.mu.Unlock()

		if err == nil {
			return nil
		}

		var permanent *backoff.PermanentError
		if errors.As(err, &permanent) {
			return permanent.Err
		}

		next := b.NextBackOff()
		if next == backoff.Stop {
			return err
		}

		select {
		case <-time.After(next):
		case <-ctx.Done():
			return ctx.Err()
		}
	}

	return fmt.Errorf("error after exhasuting retries: %w", err)
}

// NoRows reports whether err is a sql.ErrNoRows "not found" result. Use this
// instead of errors.Is(err, sql.ErrNoRows) for readability at call sites.
func NoRows(err error) bool {
	return err != nil && errors.Is(err, sql.ErrNoRows)
}

// ErrKeyNotAvailable is returned by an encrypted Pool when the data key for a
// user is not in the in-memory key store.
var ErrKeyNotAvailable = errors.New("data key not available")

// ErrEncryptionNotSupported is returned by OpenEncryptedDB and NewEncryptedPool
// when the active driver does not support SQLCipher encryption. Use the
// jgiannuzzi fork of mattn/go-sqlite3 and pass WithDriver(MattnDriver).
var ErrEncryptionNotSupported = errors.New(
	"encryption requires a SQLCipher-enabled driver; " +
		"use the jgiannuzzi fork of mattn/go-sqlite3 with WithDriver(sqlflow.MattnDriver)",
)

// Pool is a per-key connection pool backed by a ristretto cache with TinyLFU
// eviction. Each key (e.g. user ID) gets its own SQLite database file under
// dir. When the cache evicts an entry, its DB is closed only after all
// in-flight operations finish (reference-counted via poolEntry).
type Pool[Queries any, D DBTX] struct {
	// dir is the directory under which per-key *.db files are stored.
	dir string

	// querier constructs the per-transaction accessor for each opened DB.
	querier Querier[Queries, D]

	// mu serialises DB creation so only one goroutine opens a new file at a
	// time (double-checked locking with the cache).
	mu sync.Mutex

	// cache is the ristretto TinyLFU cache mapping keys to open poolEntries.
	cache *ristretto.Cache[string, *poolEntry[Queries, D]]

	// keyProvider returns the SQLCipher key for a given pool key. Nil for
	// unencrypted pools.
	keyProvider func(userID string) ([]byte, bool)

	// inactivityTimeout is the idle duration after which a pool entry is
	// evicted by the background reaper. Zero means no reaper is running.
	inactivityTimeout time.Duration

	// reapCancel stops the current background inactivity reaper goroutine.
	// Nil when no reaper is running. Protected by mu.
	reapCancel context.CancelFunc

	// opts is the fixed set of DB options applied to every database opened by
	// this pool. Callers are responsible for ensuring any shared state in
	// option closures is safe for concurrent use.
	opts []Option
}

// NewPool creates a plain (unencrypted) Pool backed by on-disk SQLite
// databases. maxCached controls the maximum number of open databases kept in
// the cache (minimum 1000). opts are applied to every database opened by the
// pool. Call SetInactivityTimeout to enable the background eviction reaper.
func NewPool[Queries any, D DBTX](
	dir string, querier Querier[Queries, D], maxCached int64, opts ...Option,
) (*Pool[Queries, D], error) {
	return newPool(dir, querier, maxCached, nil, opts)
}

// NewEncryptedPool creates a Pool where each database is encrypted with
// SQLCipher. keyProvider is called with the pool key (e.g. user ID) each time
// a database is opened; it must return the 32-byte encryption key and true, or
// false if the key is unavailable (causing Read/Write to return
// ErrKeyNotAvailable). opts are applied to every database opened by the pool.
// Call SetInactivityTimeout to enable the background eviction reaper.
//
// Encryption requires a SQLCipher-enabled driver. Use the jgiannuzzi fork of
// mattn/go-sqlite3 and pass WithDriver(MattnDriver) (the default). Other
// drivers return ErrEncryptionNotSupported when the first database is opened.
func NewEncryptedPool[Queries any, D DBTX](
	dir string, querier Querier[Queries, D], maxCached int64,
	keyProvider func(string) ([]byte, bool), opts ...Option,
) (*Pool[Queries, D], error) {
	return newPool(dir, querier, maxCached, keyProvider, opts)
}

// TestPool returns a plain pool backed by dir for tests. Panics on error,
// matching the TestDB convention.
func TestPool[Queries any, D DBTX](dir string, querier Querier[Queries, D], opts ...Option) *Pool[Queries, D] {
	p, err := NewPool(dir, querier, 100_000, opts...)
	if err != nil {
		panic(fmt.Sprintf("creating test pool: %v", err))
	}

	return p
}

// Evict immediately removes the pool entry for userID from the cache, closing
// the database once all in-flight operations finish. No-op if the entry is not
// cached.
func (p *Pool[Queries, D]) Evict(userID string) {
	p.cache.Del(userID)
}

// Wait blocks until all pending cache evictions have been processed.
func (p *Pool[Queries, D]) Wait() {
	p.cache.Wait()
}

// Read acquires the database for key and executes f inside a read-only
// deferred transaction. The pool entry's reference count is held for the
// duration so the database is not closed while f is running.
func (p *Pool[Queries, D]) Read(ctx context.Context, key string, f func(*Queries) error) error {
	entry, err := p.acquire(key)
	if err != nil {
		return err
	}
	defer entry.release()

	return entry.db.Read(ctx, f)
}

// Write acquires the database for key and executes f inside an immediate
// (exclusive) transaction. The pool entry's reference count is held for the
// duration so the database is not closed while f is running.
func (p *Pool[Queries, D]) Write(ctx context.Context, key string, f func(*Queries) error) error {
	entry, err := p.acquire(key)
	if err != nil {
		return err
	}
	defer entry.release()

	return entry.db.Write(ctx, f)
}

// ListKeys returns the key (user ID) for every database file in the pool
// directory. The returned slice is sorted by filesystem order.
func (p *Pool[Queries, D]) ListKeys() ([]string, error) {
	matches, err := filepath.Glob(filepath.Join(p.dir, "*.db"))
	if err != nil {
		return nil, fmt.Errorf("listing pool keys: %w", err)
	}

	keys := make([]string, 0, len(matches))
	for _, path := range matches {
		key := strings.TrimSuffix(filepath.Base(path), ".db")
		keys = append(keys, key)
	}

	return keys, nil
}

// SetInactivityTimeout starts a background reaper that evicts pool entries
// that have been idle for longer than d. Calling it again cancels the previous
// reaper and starts a new one with the updated duration. Pass 0 to stop the
// reaper without starting a new one.
func (p *Pool[Queries, D]) SetInactivityTimeout(d time.Duration) {
	p.mu.Lock()
	if p.reapCancel != nil {
		p.reapCancel()
		p.reapCancel = nil
	}
	p.inactivityTimeout = d
	if d > 0 {
		ctx, cancel := context.WithCancel(context.Background())
		p.reapCancel = cancel
		go p.runInactivityReaper(ctx)
	}
	p.mu.Unlock()
}

// Close stops the inactivity reaper and closes all cached databases.
// sql.DB.Close waits for in-flight operations to finish, so this blocks until
// everything drains.
func (p *Pool[Queries, D]) Close() error {
	p.mu.Lock()
	if p.reapCancel != nil {
		p.reapCancel()
	}
	p.mu.Unlock()

	var errs []error

	p.cache.IterValues(func(entry *poolEntry[Queries, D]) (stop bool) {
		entry.closing.Store(true)
		entry.once.Do(func() {
			if err := entry.db.Close(); err != nil {
				errs = append(errs, err)
			}
		})

		return false
	})
	p.cache.Close()

	return errors.Join(errs...)
}

type openFnList []func(path string, db *sql.DB) error

func (olf openFnList) run(path string, db *sql.DB) error {
	for _, fn := range olf {
		if err := fn(path, db); err != nil {
			return err
		}
	}

	return nil
}

type closeFnList []func(path string, db *sql.DB)

func (clf closeFnList) run(path string, db *sql.DB) {
	for _, fn := range clf {
		fn(path, db)
	}
}

func collectHooks(opts []Option) (openFnList, closeFnList) {
	var onOpen openFnList
	var onClose closeFnList

	for _, opt := range opts {
		if opt.onOpen != nil {
			onOpen = append(onOpen, opt.onOpen)
		}

		if opt.onClose != nil {
			onClose = append(onClose, opt.onClose)
		}
	}

	return onOpen, onClose
}

func collectDSNParams(opts []Option) url.Values {
	merged := url.Values{}

	for _, opt := range opts {
		if opt.dsnParams == "" {
			continue
		}

		params, _ := url.ParseQuery(opt.dsnParams)
		maps.Copy(merged, params)
	}

	return merged
}

func collectPragmas(opts []Option) [][2]string {
	var pragmas [][2]string

	for _, opt := range opts {
		pragmas = append(pragmas, opt.pragmas...)
	}

	return pragmas
}

func collectDriver(opts []Option) DriverConfig {
	d := MattnDriver

	for _, opt := range opts {
		if opt.driver != nil {
			d = *opt.driver
		}
	}

	return d
}

func openDB[Queries any, D DBTX](dbName string, querier Querier[Queries, D], key []byte, opts []Option) (*DB[Queries, D], error) {
	if err := os.MkdirAll(filepath.Dir(dbName), 0o755); err != nil {
		return nil, fmt.Errorf("creating db dir: %w", err)
	}

	return openDBConns(dbName, querier, key, opts)
}

func newPool[Queries any, D DBTX](
	dir string, querier Querier[Queries, D], maxCached int64,
	keyProvider func(string) ([]byte, bool),
	opts []Option,
) (*Pool[Queries, D], error) {
	maxCached = max(maxCached, 1000)

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return nil, fmt.Errorf("creating pool dir: %w", err)
	}

	p := &Pool[Queries, D]{
		dir:         dir,
		querier:     querier,
		keyProvider: keyProvider,
		opts:        opts,
	}

	cache, err := newPoolCache[Queries, D](maxCached)
	if err != nil {
		return nil, fmt.Errorf("creating pool cache: %w", err)
	}
	p.cache = cache

	return p, nil
}

func openDBConns[Queries any, D DBTX](dbName string, querier Querier[Queries, D], key []byte, opts []Option) (*DB[Queries, D], error) {
	driver := collectDriver(opts)
	params := collectDSNParams(opts)
	pragmas := collectPragmas(opts)

	var wDSN, rDSN string

	if len(key) > 0 {
		if driver.buildCipherDSN == nil {
			return nil, ErrEncryptionNotSupported
		}

		wDSN = driver.buildCipherDSN(dbName, "immediate", key, params, pragmas)
		rDSN = driver.buildCipherDSN(dbName, "deferred", key, params, pragmas)
	} else {
		wDSN = driver.buildDSN(dbName, "immediate", params, pragmas)
		rDSN = driver.buildDSN(dbName, "deferred", params, pragmas)
	}

	wrdb, err := sql.Open(driver.name, wDSN)
	if err != nil {
		return nil, err
	}
	wrdb.SetMaxOpenConns(1)

	rddb, err := sql.Open(driver.name, rDSN)
	if err != nil {
		wrdb.Close()

		return nil, err
	}

	onOpen, onClose := collectHooks(opts)

	if err := onOpen.run(dbName, wrdb); err != nil {
		rddb.Close()
		wrdb.Close()

		return nil, fmt.Errorf("onOpen hook for %q: %w", dbName, err)
	}

	return &DB[Queries, D]{
		querier:        querier,
		rddb:           rddb,
		mu:             &sync.Mutex{},
		wrdb:           wrdb,
		backoffRetries: 5,
		path:           dbName,
		onClose:        onClose,
		driver:         driver,
	}, nil
}

// runInactivityReaper periodically evicts pool entries that have been idle
// longer than p.inactivityTimeout. Stops when ctx is cancelled.
func (p *Pool[Queries, D]) runInactivityReaper(ctx context.Context) {
	interval := max(p.inactivityTimeout/4, time.Second)
	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			p.reapInactive()
		}
	}
}

func (p *Pool[Queries, D]) reapInactive() {
	cutoff := time.Now().Add(-p.inactivityTimeout).UnixNano()

	// Collect keys first; calling Del inside IterValues would deadlock because
	// IterValues holds a read lock and Del needs a write lock on the same shard.
	var toEvict []string
	p.cache.IterValues(func(entry *poolEntry[Queries, D]) (stop bool) {
		if entry.refs.Load() == 0 && entry.lastActivity.Load() < cutoff {
			toEvict = append(toEvict, entry.key)
		}

		return false
	})
	for _, key := range toEvict {
		p.cache.Del(key)
	}
}

// acquire returns a poolEntry with an incremented ref count. The caller must
// call release when done. If the entry is being evicted, acquire retries with
// a fresh entry.
func (p *Pool[Queries, D]) acquire(key string) (*poolEntry[Queries, D], error) {
	for {
		entry, err := p.getOrCreate(key)
		if err != nil {
			return nil, err
		}
		if entry.acquire() {
			entry.lastActivity.Store(time.Now().UnixNano())

			return entry, nil
		}
		// Entry is closing (evicted). Loop to create a replacement.
	}
}

func (p *Pool[Queries, D]) getOrCreate(key string) (*poolEntry[Queries, D], error) {
	if entry, ok := p.cache.Get(key); ok {
		return entry, nil
	}

	p.mu.Lock()
	defer p.mu.Unlock()

	// Double-check after acquiring lock.
	if entry, ok := p.cache.Get(key); ok {
		return entry, nil
	}

	dbPath := filepath.Join(p.dir, key+".db")

	var dbKey []byte
	if p.keyProvider != nil {
		k, ok := p.keyProvider(key)
		if !ok {
			return nil, fmt.Errorf("%w for user %q — please log in again", ErrKeyNotAvailable, key)
		}
		dbKey = k
	}

	newDB, err := openDB(dbPath, p.querier, dbKey, p.opts)
	if err != nil {
		return nil, fmt.Errorf("opening db for %q: %w", key, err)
	}

	entry := &poolEntry[Queries, D]{
		key: key,
		db:  newDB,
	}
	entry.lastActivity.Store(time.Now().UnixNano())
	p.cache.Set(key, entry, 1)
	p.cache.Wait()

	return entry, nil
}

// poolEntry wraps a DB with reference counting so that evicted databases are
// not closed while goroutines are still using them.
type poolEntry[Queries any, D DBTX] struct {
	// key is the pool key (e.g. user ID) that identifies this entry.
	key string

	// db is the open database for this key.
	db *DB[Queries, D]

	// lastActivity records the last acquire time as unix nanoseconds; used by
	// the inactivity reaper to decide whether to evict the entry.
	lastActivity atomic.Int64

	// refs counts the number of active Read/Write callers holding this entry.
	refs atomic.Int32

	// closing is set to true when the entry has been evicted from the cache.
	// New acquires on a closing entry are rejected so a fresh entry is created.
	closing atomic.Bool

	// once ensures the database is closed exactly once regardless of how many
	// goroutines race to release or evict the entry.
	once sync.Once
}

func (e *poolEntry[Queries, D]) acquire() bool {
	e.refs.Add(1)
	if e.closing.Load() {
		e.release()

		return false
	}

	return true
}

func (e *poolEntry[Queries, D]) release() {
	if e.refs.Add(-1) == 0 && e.closing.Load() {
		e.once.Do(func() {
			e.db.Close()
		})
	}
}

func (e *poolEntry[Queries, D]) evict() {
	e.closing.Store(true)
	if e.refs.Load() == 0 {
		e.once.Do(func() {
			e.db.Close()
		})
	}
}

func newPoolCache[Queries any, D DBTX](maxCached int64) (*ristretto.Cache[string, *poolEntry[Queries, D]], error) {
	return ristretto.NewCache(&ristretto.Config[string, *poolEntry[Queries, D]]{
		NumCounters: maxCached * 10,
		MaxCost:     maxCached,
		BufferItems: 64,
		OnExit: func(entry *poolEntry[Queries, D]) {
			if entry != nil {
				entry.evict()
			}
		},
	})
}

// mattnBuildDSN builds a flat-param DSN for the mattn/go-sqlite3 driver.
func mattnBuildDSN(path, txlock string, userParams url.Values, pragmas [][2]string) string {
	merged := make(url.Values, len(userParams)+6)
	maps.Copy(merged, userParams)

	// Strip cipher params — use OpenEncryptedDB for encrypted databases.
	delete(merged, "_key")
	delete(merged, "_cipher")

	// Apply sqlflow defaults for tuning params the caller did not set.
	if merged.Get("_sync") == "" {
		merged.Set("_sync", "1")
	}
	if merged.Get("_busy_timeout") == "" {
		merged.Set("_busy_timeout", "5000")
	}
	if merged.Get("_cache_size") == "" {
		merged.Set("_cache_size", "10000")
	}

	// Apply WithPragma pragmas as flat params, skipping locked ones.
	for _, p := range pragmas {
		if strings.EqualFold(p[0], "journal_mode") || strings.EqualFold(p[0], "txlock") {
			continue
		}
		merged.Set("_"+p[0], p[1])
	}

	// Lock correctness-critical params — these always win.
	merged.Set("_journal", "wal")
	merged.Set("_txlock", txlock)

	return path + "?" + merged.Encode()
}

// mattnBuildCipherDSN builds an encrypted DSN for the jgiannuzzi fork of
// mattn/go-sqlite3. The fork applies PRAGMA key before any file-accessing
// pragmas so that WAL and synchronous settings work correctly on existing
// encrypted databases.
func mattnBuildCipherDSN(path, txlock string, key []byte, userParams url.Values, pragmas [][2]string) string {
	merged := make(url.Values, len(userParams)+7)
	maps.Copy(merged, userParams)

	// Apply sqlflow defaults for tuning params the caller did not set.
	if merged.Get("_sync") == "" {
		merged.Set("_sync", "1")
	}
	if merged.Get("_busy_timeout") == "" {
		merged.Set("_busy_timeout", "5000")
	}
	if merged.Get("_cache_size") == "" {
		merged.Set("_cache_size", "10000")
	}

	// Apply WithPragma pragmas as flat params, skipping locked ones.
	for _, p := range pragmas {
		if strings.EqualFold(p[0], "journal_mode") || strings.EqualFold(p[0], "txlock") {
			continue
		}
		merged.Set("_"+p[0], p[1])
	}

	// Lock correctness-critical and cipher params — these always win.
	merged.Set("_journal", "wal")
	merged.Set("_txlock", txlock)
	merged.Set("_cipher", "sqlcipher")
	merged.Set("_key", "x'"+hex.EncodeToString(key)+"'")

	return path + "?" + merged.Encode()
}

// pragmaQueryValues builds the shared url.Values for pragma-style DSNs used
// by the modernc and ncruces drivers. It applies defaults, user overrides, and
// locked params using the _pragma=name(value) query format.
func pragmaQueryValues(txlock string, userParams url.Values, pragmas [][2]string) url.Values {
	result := make(url.Values)

	// Collect user _pragma values, filtering the locked journal_mode.
	var userPragmaVals []string
	for _, pv := range userParams["_pragma"] {
		if strings.HasPrefix(strings.ToLower(strings.TrimSpace(pv)), "journal_mode(") {
			continue
		}
		userPragmaVals = append(userPragmaVals, pv)
	}

	// Translate overridable flat params (_sync, _busy_timeout, _cache_size) from
	// WithDSNParams into pragma equivalents so they work for modernc/ncruces too.
	// These map mattn flat-param names to their SQLite pragma names.
	flatToPragma := [][2]string{
		{"_sync", "synchronous"},
		{"_busy_timeout", "busy_timeout"},
		{"_cache_size", "cache_size"},
	}
	for _, mapping := range flatToPragma {
		if v := userParams.Get(mapping[0]); v != "" {
			userPragmaVals = append(userPragmaVals, mapping[1]+"("+v+")")
		}
	}

	// Copy non-pragma, non-locked flat params from userParams.
	// Underscore-prefixed params (_name=value) are mattn-style pragma shortcuts;
	// translate them to pragma(value) format so they work on modernc/ncruces too.
	for k, vals := range userParams {
		switch k {
		case "_key", "_cipher", "_txlock", "_journal", "_sync", "_busy_timeout", "_cache_size":
			// Skip — locked, cipher-only, or already handled via flatToPragma above.
		case "_pragma":
			// Already collected above.
		default:
			if strings.HasPrefix(k, "_") {
				pragmaName := k[1:]
				for _, v := range vals {
					userPragmaVals = append(userPragmaVals, pragmaName+"("+v+")")
				}
			} else {
				result[k] = vals
			}
		}
	}

	// hasPragma reports whether name is already set by the user.
	hasPragma := func(name string) bool {
		prefix := strings.ToLower(name) + "("
		for _, pv := range userPragmaVals {
			if strings.HasPrefix(strings.ToLower(strings.TrimSpace(pv)), prefix) {
				return true
			}
		}
		for _, p := range pragmas {
			if strings.EqualFold(p[0], name) {
				return true
			}
		}

		return false
	}

	// Add sqlflow defaults only if not already set by the caller.
	if !hasPragma("synchronous") {
		result.Add("_pragma", "synchronous(NORMAL)")
	}
	if !hasPragma("busy_timeout") {
		result.Add("_pragma", "busy_timeout(5000)")
	}
	if !hasPragma("cache_size") {
		result.Add("_pragma", "cache_size(10000)")
	}

	// Add user _pragma values (already filtered above).
	for _, pv := range userPragmaVals {
		result.Add("_pragma", pv)
	}

	// Add WithPragma pragmas, skipping the locked journal_mode.
	for _, p := range pragmas {
		if strings.EqualFold(p[0], "journal_mode") {
			continue
		}
		result.Add("_pragma", p[0]+"("+p[1]+")")
	}

	// Lock journal_mode and txlock — these always win.
	result.Add("_pragma", "journal_mode(WAL)")
	result.Set("_txlock", txlock)

	return result
}

// pragmaBuildDSN builds a file: URI DSN using the _pragma=name(value) format
// used by the modernc and ncruces drivers.
func pragmaBuildDSN(path, txlock string, userParams url.Values, pragmas [][2]string) string {
	q := pragmaQueryValues(txlock, userParams, pragmas)

	return "file:" + path + "?" + q.Encode()
}

// pragmaInMemoryDSN builds an in-memory DSN for pragma-style drivers.
// name is the database name in the URI (unique per TestDB call for drivers that
// require shared-cache). shared adds cache=shared, which is required by modernc
// for in-memory databases opened across multiple connections.
func pragmaInMemoryDSN(shared bool, name, txlock string, userParams url.Values, pragmas [][2]string) string {
	q := pragmaQueryValues(txlock, userParams, pragmas)
	q.Set("mode", "memory")

	if shared {
		q.Set("cache", "shared")
	}

	return "file:" + name + "?" + q.Encode()
}

func (db *DB[Queries, D]) transaction(ctx context.Context, rdbms *sql.DB, f func(*Queries) error) error {
	tx, err := rdbms.BeginTx(ctx, nil)
	if err != nil {
		// "sql: database is closed" means Close was called — retrying is pointless.
		if strings.Contains(err.Error(), "database is closed") {
			return backoff.Permanent(fmt.Errorf("error creating transaction: %w", err))
		}

		// Driver-specific permanent errors (e.g. SQLITE_NOTADB for mattn).
		if db.driver.isPermanentErr(err) {
			return backoff.Permanent(fmt.Errorf("error creating transaction: %w", err))
		}

		return fmt.Errorf("error creating transaction: %w", err)
	}

	// Go's type system does not allow assigning a concrete value (*sql.Tx) to a
	// type parameter (D) directly, even when the concrete type satisfies the
	// constraint. Boxing through any and asserting back to D is the standard
	// generics workaround for this limitation.
	querier := db.querier(any(tx).(D))

	if err := f(querier); err != nil {
		if rbErr := tx.Rollback(); rbErr != nil {
			return errors.Join(err, rbErr)
		}

		return backoff.Permanent(err)
	}

	return tx.Commit()
}
